-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgME/na+0e/EYbsC8M
TeJR2EBqaVPPZatw5MeaiQu9XHugCgYIKoZIzj0DAQehRANCAAQ2wrpn1rKvZmlW
SZ2NZuc2vIZtYAbzxiDrQ/BsrN8PVlH/C5wGBDtf4oeAuFw/457BmzrEZxD/8/Cz
YO2CW0ee
-----END PRIVATE KEY-----